package views;

import java.awt.*;
import javax.swing.*;
import org.netbeans.lib.awtextra.*;

public class LogInView extends javax.swing.JPanel {

    /**
     * Creates new form A
     */
    public LogInView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        jPanel2 = new JPanel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel8 = new JLabel();
        logInB = new JButton();
        tenF = new JTextField();
        passF = new JPasswordField();

        setMinimumSize(new Dimension(600, 400));
        setPreferredSize(new Dimension(600, 400));
        setLayout(new AbsoluteLayout());
        add(jLabel1, new AbsoluteConstraints(0, 0, 30, 500));

        jPanel2.setLayout(new AbsoluteLayout());

        jLabel4.setBackground(new Color(0, 0, 0));
        jLabel4.setFont(new Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(SwingConstants.LEFT);
        jLabel4.setText("Quản lý kho vũ khĩ");
        jLabel4.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel4, new AbsoluteConstraints(30, 20, 370, -1));

        jLabel5.setBackground(new Color(0, 0, 0));
        jLabel5.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Tên đăng nhập");
        jPanel2.add(jLabel5, new AbsoluteConstraints(30, 110, 140, -1));

        jLabel8.setBackground(new Color(0, 0, 0));
        jLabel8.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Mật khẩu");
        jPanel2.add(jLabel8, new AbsoluteConstraints(30, 200, 140, -1));

        logInB.setBackground(new Color(204, 204, 204));
        logInB.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        logInB.setText("ĐĂNG NHẬP");
        logInB.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jPanel2.add(logInB, new AbsoluteConstraints(30, 290, 360, 40));

        tenF.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        tenF.setOpaque(true);
        jPanel2.add(tenF, new AbsoluteConstraints(30, 140, 360, 30));

        passF.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(passF, new AbsoluteConstraints(30, 230, 360, 30));

        add(jPanel2, new AbsoluteConstraints(50, 0, 430, 400));
    }// </editor-fold>//GEN-END:initComponents

    public JButton getLogInB() {
        return logInB;
    }

    public JTextField getTenF() {
        return tenF;
    }

    public JTextField getPassF() {
        return passF;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel jLabel1;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel8;
    private JPanel jPanel2;
    private JButton logInB;
    private JPasswordField passF;
    private JTextField tenF;
    // End of variables declaration//GEN-END:variables
}
