/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author _____
 */
public class PhanLoaiView extends javax.swing.JPanel {

    /**
     * Creates new form PhanLoai
     */
    public PhanLoaiView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        findF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        findBtn = new javax.swing.JButton();
        setB = new javax.swing.JButton();
        addB = new javax.swing.JButton();
        editB = new javax.swing.JButton();
        delB = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 560, 40, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tìm kiếm");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("PHÂN LOẠI");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        nameF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFActionPerformed(evt);
            }
        });
        add(nameF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 230, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stt", "Mã", "Tên phân loại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(1).setMinWidth(150);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(150);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 770, -1));

        findF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findFActionPerformed(evt);
            }
        });
        add(findF, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 230, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Tên phân loại");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        findBtn.setText("Tìm kiếm");
        findBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBtnActionPerformed(evt);
            }
        });
        add(findBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, -1, -1));

        setB.setText("Reset");
        setB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setBActionPerformed(evt);
            }
        });
        add(setB, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 540, 90, -1));

        addB.setText("Thêm");
        addB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBActionPerformed(evt);
            }
        });
        add(addB, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 90, -1));

        editB.setText("Sửa");
        editB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBActionPerformed(evt);
            }
        });
        add(editB, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 540, 90, -1));

        delB.setText("Xóa");
        delB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBActionPerformed(evt);
            }
        });
        add(delB, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nameFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFActionPerformed

    private void findFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findFActionPerformed

    private void findBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findBtnActionPerformed

    private void setBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setBActionPerformed

    private void addBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBActionPerformed

    private void editBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBActionPerformed

    private void delBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delBActionPerformed

    public JButton getFindBtn() {
        return findBtn;
    }

    public JButton getDelB() {
        return delB;
    }

    public JButton getEditB() {
        return editB;
    }

    public JButton getAddB() {
        return addB;
    }
    
    public JButton getClearBtn() {
        return setB;
    }

    public JTextField getFindF() {
        return findF;
    }

    public JTextField getNameF() {
        return nameF;
    }
    
    public JTable getTable() {
        return jTable1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addB;
    private javax.swing.JButton delB;
    private javax.swing.JButton editB;
    private javax.swing.JButton findBtn;
    private javax.swing.JTextField findF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameF;
    private javax.swing.JButton setB;
    // End of variables declaration//GEN-END:variables
}
