/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author _____
 */
public class PhieuNhapView extends javax.swing.JPanel {

    /**
     * Creates new form PhieuXuatView
     */
    public PhieuNhapView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        clrB = new javax.swing.JButton();
        addB = new javax.swing.JButton();
        editB = new javax.swing.JButton();
        delB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        sDate = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        eDate = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 550, 40, 50));

        clrB.setText("Bỏ chọn");
        add(clrB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 100, -1));

        addB.setText("Thêm");
        add(addB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 100, -1));

        editB.setText("Sửa");
        add(editB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 100, -1));

        delB.setText("Xóa");
        delB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBActionPerformed(evt);
            }
        });
        add(delB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 100, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel2.setText("PHIẾU NHẬP");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 50));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stt", "Mã", "Ngày phát", "Ngày thu", "Đã thu", "Chưa thu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.getTableHeader().setResizingAllowed(false);
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(4).setResizable(false);
            table.getColumnModel().getColumn(5).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 700, -1));

        sDate.setDateFormatString("dd-MM-yyyy");
        add(sDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 240, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setText("Ngày phát");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        eDate.setDateFormatString("dd-MM-yyyy");
        add(eDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 240, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("Ngày thu");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void delBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delBActionPerformed

    public JButton getAddB() {
        return addB;
    }

    public JButton getEditB() {
        return editB;
    }

    public JButton getDelBtn() {
        return delB;
    }

    public JButton getClrB() {
        return clrB;
    }
    
    public JTable getTable() {
        return table;
    }
    
    public JDateChooser getEDate() {
        return eDate;
    }
    
    public JDateChooser getSDate() {
        return sDate;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addB;
    private javax.swing.JButton clrB;
    private javax.swing.JButton delB;
    private com.toedter.calendar.JDateChooser eDate;
    private javax.swing.JButton editB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser sDate;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
