/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author _____
 */
public class VuKhiView extends javax.swing.JPanel {

    /**
     * Creates new form VuKhiView
     */
    public VuKhiView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        prF = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        reF = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        pnF = new javax.swing.JComboBox<>();
        plF = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        clrB = new javax.swing.JButton();
        addB = new javax.swing.JButton();
        editB = new javax.swing.JButton();
        delB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        minP = new javax.swing.JSpinner();
        maxP = new javax.swing.JSpinner();
        findB = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("VŨ KHÍ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 22, 155, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("Tên vũ khí");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, -1));
        add(nameF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 230, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setText("VND");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 40, -1));
        add(prF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 100, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("Giá thành");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setText("Phiếu nhập");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 80, -1));

        reF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reFActionPerformed(evt);
            }
        });
        add(reF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setText("Thu về");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 110, -1));

        pnF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnFActionPerformed(evt);
            }
        });
        add(pnF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 130, -1));

        plF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        plF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plFActionPerformed(evt);
            }
        });
        add(plF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 130, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel7.setText("Phân loại");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 80, -1));

        clrB.setText("Bỏ chọn");
        add(clrB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 100, -1));

        addB.setText("Thêm");
        add(addB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 100, -1));

        editB.setText("Sửa");
        add(editB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 100, -1));

        delB.setText("Xóa");
        delB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBActionPerformed(evt);
            }
        });
        add(delB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 100, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stt", "Tên vũ khí", "Thu về", "Phân loại", "Mã phiếu nhập", "Giá thành"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.getTableHeader().setResizingAllowed(false);
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 720, 480));
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 550, 40, 50));

        jLabel9.setText("Giá nhỏ nhất");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        jLabel10.setText("Giá cao nhất");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));
        add(minP, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 110, -1));

        maxP.setModel(new javax.swing.SpinnerNumberModel(10000000, null, 10000000, 1));
        add(maxP, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 110, -1));

        findB.setText("Tìm kiếm");
        findB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBActionPerformed(evt);
            }
        });
        add(findB, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void reFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reFActionPerformed

    private void pnFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnFActionPerformed

    private void plFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plFActionPerformed

    private void delBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delBActionPerformed

    private void findBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findBActionPerformed

    public JButton getAddB() {
        return addB;
    }

    public JButton getEditB() {
        return editB;
    }

    public JButton getDelBtn() {
        return delB;
    }

    public JButton getClrB() {
        return clrB;
    }

    public JTable getTable() {
        return table;
    }

    public JComboBox getPhanLoai() {
        return plF;
    }

    public JComboBox getPhieuNhap() {
        return pnF;
    }

    public JSpinner getGia() {
        return prF;
    }

    public JCheckBox getThuHoi() {
        return reF;
    }

    public JTextField getTen() {
        return nameF;
    }

    public JButton getFindB() {
        return findB;
    }
    
    public JSpinner getMaxP() {
        return maxP;
    }

    public JSpinner getMinP() {
        return minP;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addB;
    private javax.swing.JButton clrB;
    private javax.swing.JButton delB;
    private javax.swing.JButton editB;
    private javax.swing.JButton findB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner maxP;
    private javax.swing.JSpinner minP;
    private javax.swing.JTextField nameF;
    private javax.swing.JComboBox<String> plF;
    private javax.swing.JComboBox<String> pnF;
    private javax.swing.JSpinner prF;
    private javax.swing.JCheckBox reF;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
